config/routes.rb
Rails.application.routes.draw do
  
  root to: 'locations#home'

  get '/auth/:provider/callback' => 'sessions#create_google'
  get 'auth/failure', to: redirect('/')

 resources :users do
    resources :locations
  end

  get 'users/:id/locations/:id' => 'users#show', :as => :user_location_path

  resources :locations
  resources :users
  
  resources :sessions, only: [:new, :create, :destroy]
  
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  #resources :locations do
    #resources :edibles
  #end


  end

app/models/user.rb
class User < ApplicationRecord

	has_secure_password

    has_many :locations
    #has_many :edibles, through: :locations
    accepts_nested_attributes_for :locations

  	validates :username, presence: true, uniqueness: true

  	validates :password, presence: :true
                       #:confirmation => true,
                       #:length => { minimum: 6 },
                       #:unless => :already_has_password?

  
	def self.find_or_create_from_auth_hash(auth)
		where(uid: auth.uid).first_or_initialize.tap do |user|
			user.uid = auth.uid
			user.email = auth.info.email
			user.image = auth.info.image
			user.save!
		end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:edit, :update, :destroy]
	before_action :authorize_user, only: [:edit, :update, :destroy]
	
	
	def new
		@user = User.new
	end

	def index
		@user = User.find(params[:id])
		@locations = @user.locations
		redirect_to user_locations_path
	end


	def create

	    @user = User.new(user_params)
	    if @user.save
	      session[:user_id] = @user.id
	      redirect_to user_path(@user), notice: "You are signed up"
	    else
	      render 'new'
	    end
  	end
  
  def show
  		redirect_to location_path
    end

private

    def user_params
    	params.require(:user).permit(:username, :password, :edible_ids => [], edibles_attributes: [:name])
  	end

  	def authorize_user
      redirect_to root_path unless @user == current_user
      #some error message would be useful
    end
  end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
  <%= render 'layouts/form_errors' %>

  
	<%= f.label :username, 'Username:' %>
  	<div><%= f.text_field :username %> <br></div>

  	<%= f.label :password, 'Password:' %>
  	<div><%= f.text_field :password %></div>

  	

app/views/users/index.html.erb
<%= stylesheet_link_tag "application" %>
 <div class="wrapper">

<% if !@locations.empty? %>
  
<h2>List of locations entered by <%= current_user.username %> </h2>
   
Click on a location ID for more information:
<br>
 <br>
<% @locations.each do |location| %>
<li>
    <h3>#<%= link_to location.id, user_location_path(location.user, location) %>: </h3>
       Address: <%= location.address %>, 
       Latitude: <%= location.lat %>, 
       Longitude: <%= location.lng %>
</li>
<% end %>

<% else %>

<h3>Your location library is currently empty. </h3>
<br>
Please add a location or check out the locations that have already been entered using the menu bove.

<% end %>
		
</div>

app/views/users/new.html.erb
<%= stylesheet_link_tag "application" %>
 <div class="wrapper">


<h3>Please sign up here:</h3>
<br>
	<%= form_for @user do |f| %>
		<%= render 'users/form',  f: f %>
		<br>
	 <%= f.submit "Submit" %>

<% end %>


</div>

app/views/users/show.html.erb
<%= stylesheet_link_tag "application" %>
<div class="wrapper">

<h2>Details of location:</h2>

<h3>Location id: 
    #<%= @location_id %> </h3>

<h3>Address:</h3>
    <%= @location_address %> 
<br>
<h3>Latitude:</h3>
    <%= @location_lat %> 
<br>
<h3>Longitude:</h3>
    <%= @location_lng %> 

<h3>Location description:</h3>
<%= @location_description %>
<br>

<h3>Location type:</h3>
    <%= @location_loc_type %> 
<br>

<h3>Food available:</h3>


<%= @edibles.each do |e| %>

  <%= e.name %>
<% end %>


<br>


<br>
<br>

<%= link_to "Edit this Location", edit_user_location_path(current_user)%>
<%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } 			%>


</div>