config/routes.rb
Rails.application.routes.draw do
  
  root to: 'locations#home'

  get '/auth/:provider/callback' => 'sessions#create_google'
  get 'auth/failure', to: redirect('/')

 resources :users do
    resources :locations
  end

  get 'users/:id/locations/:id' => 'users#show', :as => :user_location_path

  resources :locations
  resources :users
  
  resources :sessions, only: [:new, :create, :destroy]
  
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  #resources :locations do
    #resources :edibles
  #end


  end

app/views/layouts/_header.html.erb
<% if current_user %>

Welcome <%= current_user.username %> 

	
		<%= link_to "My Locations", user_locations_path(current_user) %> |

		<%= link_to "Create a Location", new_user_location_path(current_user) %>
<% end %>

<div><center>
	<% if flash.now[:notice] %>
<%= flash.now[:notice] %>
<% end %>
</div>

app/views/layouts/_navigation.html.erb
<!DOCTYPE html>
<html>
    <head>
        <style>
            .dropbtn {
                background-color: #656865;
                color: white;
                padding: 15px 57px;
                font-size: 16px;
                border: none;
            }

            .dropdown {
                position: relative;
                display: inline-block;
            }

            .dropdown-content {
                display: none;
                position: absolute;
                background-color: #f1f1f1;
                min-width: 160px;
                box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
                z-index: 1;
            }

            .dropdown-content a {
                color: black;
                padding: 15px 16px;
                text-decoration: none;
                display: block;
            }
            .dropdown-content a:hover {background-color: #ddd;}

            .dropdown:hover .dropdown-content {display: block;}

            .dropdown:hover .dropbtn {background-color: #656865;}

        </style>
     </head>


<div class="dropdown">
  <button class="dropbtn">MENU</button>
  <div class="dropdown-content">
    <%= link_to "Home", root_path %>
    <%= link_to 'Log in', login_path %>
    <%= link_to 'Sign up', signup_path %>
    <%= link_to "All Locations", locations_path %>
    <%#= link_to "My Locations", user_locations_path(current_user) %> |
    <%#= link_to "Create a Location", new_user_location_path(current_user) %>
    <%= link_to 'Log out', logout_path, method: :distroy %> 

  </div>
</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1" />

  <title>GleanMeSinatraApp</title>

  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  
</head>
<body>

<nav>
	<%= render partial: "layouts/form_errors" %>

    <%= render 'layouts/navigation' %>

    <%= render 'layouts/header' %>
 
    
</nav>
	
    <%= yield %>


 </body>
  
  
  </html>